CREATE TABLE SWEET_AUTH_TENANT  (
   TENANT_ID            BIGINT            NOT NULL  AUTO_INCREMENT   PRIMARY KEY,
   TENANT_PARENT_ID     BIGINT ,
   TENANT_CODE          VARCHAR(16)		  NOT NULL,
   TENANT_SHORTNAME     VARCHAR(32),
   TENANT_NAME          VARCHAR(128),
   TENANT_CONTACTER     VARCHAR(64),
   TENANT_PHONE         VARCHAR(16),
   TENANT_ADDRESS       VARCHAR(256),
   TENANT_CREATEDON     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   TENANT_MODIFIEDON    DATETIME,
   TENANT_STATUS        TINYINT			  DEFAULT 1,
   TENANT_ISDEL         TINYINT			  DEFAULT 0
);

CREATE TABLE SWEET_AUTH_ORG  (
   ORG_ID            	BIGINT            NOT NULL  AUTO_INCREMENT   PRIMARY KEY,
   ORG_PARENT_ID     	BIGINT ,
   ORG_CODE          	VARCHAR(16),
   ORG_NAME     		VARCHAR(128)	  NOT NULL,
   ORG_RESPONSIBLE_ID   BIGINT COMMENT '组织的负责人ID',
   ORG_SERIALNO			BIGINT ,
   ORG_TENANT_ID    	BIGINT ,
   ORG_CREATEDON     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   ORG_MODIFIEDON    	DATETIME,
   ORG_STATUS           TINYINT			  DEFAULT 1,
   ORG_ISDEL         	TINYINT			  DEFAULT 0
);

CREATE TABLE SWEET_AUTH_POST  (
   POST_ID            	BIGINT            NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
   POST_ORG_ID     	    BIGINT 			  NOT NULL,
   POST_CODE          	VARCHAR(16),
   POST_NAME     		VARCHAR(128)	  NOT NULL,  
   POST_TENANT_ID    	BIGINT ,
   POST_CREATEDON     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   POST_MODIFIEDON    	DATETIME,
   POST_ISDEL         	TINYINT			  DEFAULT 0
);

CREATE TABLE SWEET_AUTH_USER  (
   USER_ID               BIGINT            NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
   USER_CODE             VARCHAR(16)	   NOT NULL,
   USER_NAME             VARCHAR(32)	   NOT NULL,
   USER_PINGYIN          VARCHAR(32),
   USER_PASSWORD         VARCHAR(128),
   USER_FORCEMODIFYPSW   TINYINT,
   USER_MOBILE     		 VARCHAR(16),
   USER_EMAIL     		 VARCHAR(64),
   USER_IMG     		 VARCHAR(128),
   USER_SIGN    		 VARCHAR(512) COMMENT '用户签名',
   USER_ROLE    		 TINYINT COMMENT '1，平台管理员；2，租户管理员；3，用户',
   USER_INIT    		 TINYINT COMMENT '0，普通用户；1，初始化用户（无法删除）',
   USER_TENANT_ID    	 BIGINT ,
   USER_ORG_ID    		 BIGINT ,
   USER_POST_ID    	 	 BIGINT ,
   USER_LOCKTIME         DATETIME ,
   USER_CREATEDON     	 TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   USER_MODIFIEDON    	 DATETIME ,
   USER_STATUS           TINYINT			DEFAULT 1,
   USER_ISDEL         	 TINYINT			DEFAULT 0
);

CREATE TABLE SWEET_AUTH_MENU
(
  MENU_ID      			BIGINT  			NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
  MENU_PARENT_ID   		BIGINT ,
  MENU_NAME    			VARCHAR(64) 		NOT NULL,
  MENU_TYPE 			TINYINT COMMENT '1，框架页面；2，内部页面；3，功能', 
  MENU_AUTH_LEVEL      	TINYINT 			DEFAULT 3 COMMENT '对应于用户角色，1，表示仅平台管理员访问；2，表示仅租户管理员访问；3，表示用户',
  MENU_VISIBILITY   	TINYINT				DEFAULT 0 COMMENT '0，需要管理员分配后可见；1，无需管理员分配，普通用户都有的功能；',
  MENU_SERIAL_NO    	TINYINT 			DEFAULT 1,
  MENU_ICONCLASS		VARCHAR(64),
  MENU_HREF				VARCHAR(128) COMMENT '对应页面的Angular地址',
  MENU_ITEM_ID      	BIGINT ,
  MENU_CREATEDON     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  MENU_MODIFIEDON    	DATETIME,
  MENU_STATUS           TINYINT				DEFAULT 1,
  MENU_CODE             varchar(64)   comment '菜单code'
);

CREATE TABLE SWEET_AUTH_ITEM
(
  ITEM_ID      			BIGINT  			NOT NULL  AUTO_INCREMENT   PRIMARY KEY,
  ITEM_TAB    			VARCHAR(50) COMMENT '功能的标签，用于做分类用，辅助做查询过滤',
  ITEM_DESCRIPTION 		VARCHAR(1024),
  ITEM_URL         		VARCHAR(256) 		NOT NULL,
  ITEM_REQUESTMETHOD	VARCHAR(6),
  ITEM_CREATEDON     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ITEM_MODIFIEDON    	DATETIME
);

CREATE TABLE SWEET_AUTH_ITEM_PCK
(
  PCK_ID       			BIGINT  			NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
  PCK_NAME     			VARCHAR(50) 		NOT NULL,
  PCK_TENANT_ID    		BIGINT ,
  PCK_MENU_ID 			VARCHAR(1024) 		NOT NULL COMMENT '功能组包含的菜单，多个用逗号隔开',
  PCK_CREATEDON     	TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PCK_MODIFIEDON    	DATETIME
);

CREATE TABLE SWEET_AUTH_USER_PCK_MAP
(
  ID       				BIGINT  			NOT NULL  AUTO_INCREMENT   PRIMARY KEY,
  USER_ID     			BIGINT  			NOT NULL,
  PCK_ID				BIGINT 				NOT NULL,
  TENANT_ID    			BIGINT 				NOT NULL,
  CREATEDON     		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SWEET_AUTH_POST_PCK_MAP
(
  ID       				BIGINT  			NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
  POST_ID     			BIGINT  			NOT NULL,
  PCK_ID				BIGINT 				NOT NULL,
  TENANT_ID    			BIGINT 				NOT NULL,
  CREATEDON     		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SWEET_AUTH_TENANT_MENU_UNVISIBLE
(
  ID       				BIGINT  			NOT NULL   AUTO_INCREMENT  PRIMARY KEY,
  TENANT_ID     		BIGINT  			NOT NULL,
  MENU_ID				BIGINT 				NOT NULL,  
  CREATEDON     		TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE SWEET_SEQ
(
  SEQ_ID       			BIGINT  			NOT NULL     PRIMARY KEY DEFAULT 100000
);